[env] ## tells cargo make that we're in the context of a Cargo workspace
PORT = 42069

[tasks.run]
env = { "RUST_ENV" = "development", "PORT" = "${PORT}" }
install_crate = "cargo-watch"
command = "cargo"
args = ["watch", "--ignore", "tracked_shows.json", "-x", "run"]

[tasks.styles]
command = "pnpm"
args = [
    "dlx",
    "tailwindcss",
    "-i",
    "./styles/tailwindcss.css",
    "-o",
    "./assets/main.css",
    "--watch",
]

#[tasks.build-wasix]
#command = "cargo"
#args = ["wasix", "build", "--release"]

[tasks.build-wasm]
install_crate = "wasm-pack"
command = "wasm-pack"
args = ["build", "--target", "web"]


[tasks.run-wasmer]
#depends_on = ["build-wasix"]
depends_on = ["build-wasm"]
command = "wasmer"
args = ["run", "./pkg/web_scraper_subs_rust.wasm"]
#args = ["run", "target/wasm32-wasix-wasi/release/web_scraper_subs_rust.wasm", "--net", "--env", "PORT=${PORT}", "--mapdir", "/assets:./assets"]
